# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetProx <- function(y, weights) {
    .Call('HierBasis_GetProx', PACKAGE = 'HierBasis', y, weights)
}

solveHierBasis <- function(design_mat, y, ak, weights, n, lam_min_ratio, nlam, max_lambda) {
    .Call('HierBasis_solveHierBasis', PACKAGE = 'HierBasis', design_mat, y, ak, weights, n, lam_min_ratio, nlam, max_lambda)
}

GetProxOne <- function(y, weights) {
    .Call('HierBasis_GetProxOne', PACKAGE = 'HierBasis', y, weights)
}

FitAdditive <- function(y, weights, ak, x, beta, max_lambda, lam_min_ratio, alpha, tol, p, J, n, nlam, max_iter, beta_is_zero, active_set) {
    .Call('HierBasis_FitAdditive', PACKAGE = 'HierBasis', y, weights, ak, x, beta, max_lambda, lam_min_ratio, alpha, tol, p, J, n, nlam, max_iter, beta_is_zero, active_set)
}

