# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

GetProx <- function(y, weights) {
    .Call('HierBasis_GetProx', PACKAGE = 'HierBasis', y, weights)
}

